### ISSUE TITLE
Thoughts on SRP

### ISSUE THREAD

**Issue by kwkroll32** [blachlylab/vgel#3]
The [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle) states that a module or class should only be responsible for a single aspect of the program. But, it looks like almost all the reading, writing, and logic happen in the vgel function. Would you mind if I refactored the code and created separate functions, to align with this maxim? This may be a good stepping-stone to implementing channels and goroutines.

**Comment by jblachly** [comment]
Would not refactor as this is not an OO program/paradigm.
